services:
  evakage:
    image: ghcr.io/thesteau/evakage:latest
    container_name: evakage
    restart: unless-stopped
    ports:
      - "3712:3000"
    env_file: .env
    volumes:
      - account-data:/home/node/evakage-accounts

volumes:
  account-data:
